# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_api_version=0.141.3+1.21.11
# Mod Versioning
# This project uses a hybrid of Semantic Versioning (SemVer) and the target Minecraft version.
# The format is: MOD_MAJOR.MOD_MINOR.MOD_PATCH+MINECRAFT_VERSION
#
# - MOD_MAJOR: Increment for incompatible, world-breaking changes.
# - MOD_MINOR: Increment for new features.
# - MOD_PATCH: Increment for backward-compatible bug fixes.
# - Pre-release tags (e.g., -alpha.1, -beta, -rc.2) can be appended before the '+' sign.

mod_version=1.0.2+1.21.11
maven_group=com.mrbreaknfix
archives_base_name=ui_utils
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.141.3+1.21.11